[local]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
LDAP_URL = ""
ENVIRONMENT = "local"
LOG_LEVEL = "debug"

[development]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
LDAP_URL = ""
ENVIRONMENT = "development"
LOG_LEVEL = "debug"

[staging]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
LDAP_URL = ""
ENVIRONMENT = "staging"
LOG_LEVEL = "warn"

[production]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
LDAP_URL = ""
ENVIRONMENT = "production"
LOG_LEVEL = "error"
