[local]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
ENVIRONMENT = "local"
SERVER_PORT = 3001
LOG_LEVEL = "debug"

[development]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
ENVIRONMENT = "development"
SERVER_PORT = 3000
LOG_LEVEL = "debug"

[staging]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
ENVIRONMENT = "staging"
SERVER_PORT = 3000
LOG_LEVEL = "warn"

[production]
AWS_KEY = ""
AWS_SECRET = ""
AWS_REGION = ""
COUCHDB_URL = ""
ENVIRONMENT = "production"
SERVER_PORT = 3000
LOG_LEVEL = "error"
