Parameters:
  Tag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number

  TargetGroupArn:
    Type: String

  ClusterArn:
    Type: String

  Repository:
    Type: String

  AppName:
    Type: String

  ContainerPort:
    Type: Number

  HostPort:
    Type: Number


Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-svc-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Service:
    Type: AWS::ECS::Service
    DependsOn: ECSServiceRole
    Properties:
      Cluster: !Ref ClusterArn
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Sub ${AppName}-cnt
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-${AppName}
      ContainerDefinitions:
        - Name: !Sub ${AppName}-cnt
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
# Let the Dockerfile rule in this case.
#          EntryPoint:
#            - /usr/sbin/nginx
#            - -g
#            - 'daemon off;'
          Essential: true
          Memory: 128
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref HostPort
              Protocol: HTTP
          Environment:
            - Name: Tag
              Value: !Ref Tag
            - Name: TWIG_API_LDAP_URL
              Value: ldap://todo
            - Name: TWIG_API_LOG_CONSOLE
              Value: true
            - Name: TWIG_API_LOG_FILE
              Value: true
            - Name: TWIG_API_LOG_LEVEL
              Value: info
            - Name: TWIG_API_DB_URL
              Value: http://couchdb.riglet:5984

