# Default values for couchdb chart
couchdb:
  cors: true
  corsOrigins: "*://localhost:*, *://*.local:32123, *://*.riglet"
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  type: ClusterIP
  hostName: couchdb.kube.local

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

