# Default values for twig-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: builditdigital/twig-api
  tag: latest
  pullPolicy: Always
service:
  name: twig-api
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  hostName:
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
app:
  dbUrl: http://couchdb-staging-couchdb:5984
  ldapUrl: ldap://corp.riglet.local
  logLevel: debug

